/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 22
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 16
#define ALIAS_COUNT 0
#define TOKEN_COUNT 8
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 3
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 6
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_section_header = 1,
  aux_sym_assignment_token1 = 2,
  anon_sym_EQ = 3,
  sym_key = 4,
  sym_comment = 5,
  sym_quoted_value = 6,
  sym_unquoted_value = 7,
  sym_source_file = 8,
  sym_preamble = 9,
  sym_section = 10,
  sym_assignment = 11,
  sym_value = 12,
  aux_sym_source_file_repeat1 = 13,
  aux_sym_preamble_repeat1 = 14,
  aux_sym_section_repeat1 = 15,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_section_header] = "section_header",
  [aux_sym_assignment_token1] = "assignment_token1",
  [anon_sym_EQ] = "=",
  [sym_key] = "key",
  [sym_comment] = "comment",
  [sym_quoted_value] = "quoted_value",
  [sym_unquoted_value] = "unquoted_value",
  [sym_source_file] = "source_file",
  [sym_preamble] = "preamble",
  [sym_section] = "section",
  [sym_assignment] = "assignment",
  [sym_value] = "value",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_preamble_repeat1] = "preamble_repeat1",
  [aux_sym_section_repeat1] = "section_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_section_header] = sym_section_header,
  [aux_sym_assignment_token1] = aux_sym_assignment_token1,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_key] = sym_key,
  [sym_comment] = sym_comment,
  [sym_quoted_value] = sym_quoted_value,
  [sym_unquoted_value] = sym_unquoted_value,
  [sym_source_file] = sym_source_file,
  [sym_preamble] = sym_preamble,
  [sym_section] = sym_section,
  [sym_assignment] = sym_assignment,
  [sym_value] = sym_value,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_preamble_repeat1] = aux_sym_preamble_repeat1,
  [aux_sym_section_repeat1] = aux_sym_section_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_section_header] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_assignment_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_key] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_value] = {
    .visible = true,
    .named = true,
  },
  [sym_unquoted_value] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym_preamble] = {
    .visible = true,
    .named = true,
  },
  [sym_section] = {
    .visible = true,
    .named = true,
  },
  [sym_assignment] = {
    .visible = true,
    .named = true,
  },
  [sym_value] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_preamble_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_section_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_header = 1,
  field_key = 2,
  field_value = 3,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_header] = "header",
  [field_key] = "key",
  [field_value] = "value",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 2},
  [4] = {.index = 4, .length = 2},
  [5] = {.index = 6, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_header, 0},
  [1] =
    {field_key, 0},
  [2] =
    {field_key, 0},
    {field_value, 2},
  [4] =
    {field_key, 0},
    {field_value, 3},
  [6] =
    {field_key, 0},
    {field_value, 4},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ACCEPT_TOKEN(aux_sym_assignment_token1);
      if (eof) ADVANCE(9);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(12);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(18);
      if (lookahead == '\\') ADVANCE(5);
      if (lookahead != 0) ADVANCE(1);
      END_STATE();
    case 2:
      if (lookahead == '\'') ADVANCE(18);
      if (lookahead == '\\') ADVANCE(6);
      if (lookahead != 0) ADVANCE(2);
      END_STATE();
    case 3:
      if (lookahead == ']') ADVANCE(10);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(3);
      END_STATE();
    case 4:
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(3);
      END_STATE();
    case 5:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(1);
      END_STATE();
    case 6:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(2);
      END_STATE();
    case 7:
      if (eof) ADVANCE(9);
      if (lookahead == '"') ADVANCE(20);
      if (lookahead == '\'') ADVANCE(21);
      if (lookahead == '[') ADVANCE(24);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(22);
      if (lookahead == '#' ||
          lookahead == ';') ADVANCE(17);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(27);
      END_STATE();
    case 8:
      if (eof) ADVANCE(9);
      if (lookahead == '=') ADVANCE(14);
      if (lookahead == '[') ADVANCE(4);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(8);
      if (lookahead == '#' ||
          lookahead == ';') ADVANCE(17);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(sym_section_header);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(sym_section_header);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(27);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym_assignment_token1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym_assignment_token1);
      if (eof) ADVANCE(9);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(12);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(15);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_key);
      if (lookahead == '-' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(27);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(17);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_quoted_value);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_quoted_value);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(27);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_unquoted_value);
      if (lookahead == '\n') ADVANCE(1);
      if (lookahead == '"') ADVANCE(19);
      if (lookahead == '\\') ADVANCE(25);
      if (lookahead != 0) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_unquoted_value);
      if (lookahead == '\n') ADVANCE(2);
      if (lookahead == '\'') ADVANCE(19);
      if (lookahead == '\\') ADVANCE(26);
      if (lookahead != 0) ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_unquoted_value);
      if (lookahead == '"') ADVANCE(20);
      if (lookahead == '\'') ADVANCE(21);
      if (lookahead == '[') ADVANCE(24);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(22);
      if (lookahead == '#' ||
          lookahead == ';') ADVANCE(17);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(27);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(sym_unquoted_value);
      if (lookahead == ']') ADVANCE(11);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(27);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym_unquoted_value);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(27);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym_unquoted_value);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(20);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_unquoted_value);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(21);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_unquoted_value);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(27);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 8},
  [2] = {.lex_state = 13},
  [3] = {.lex_state = 13},
  [4] = {.lex_state = 7},
  [5] = {.lex_state = 7},
  [6] = {.lex_state = 8},
  [7] = {.lex_state = 8},
  [8] = {.lex_state = 8},
  [9] = {.lex_state = 8},
  [10] = {.lex_state = 8},
  [11] = {.lex_state = 8},
  [12] = {.lex_state = 8},
  [13] = {.lex_state = 8},
  [14] = {.lex_state = 8},
  [15] = {.lex_state = 8},
  [16] = {.lex_state = 8},
  [17] = {.lex_state = 8},
  [18] = {.lex_state = 8},
  [19] = {.lex_state = 0},
  [20] = {.lex_state = 0},
  [21] = {.lex_state = 8},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_section_header] = ACTIONS(1),
    [aux_sym_assignment_token1] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_key] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym_quoted_value] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(20),
    [sym_preamble] = STATE(12),
    [sym_section] = STATE(11),
    [sym_assignment] = STATE(7),
    [aux_sym_source_file_repeat1] = STATE(11),
    [aux_sym_preamble_repeat1] = STATE(7),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_section_header] = ACTIONS(5),
    [sym_key] = ACTIONS(7),
    [sym_comment] = ACTIONS(9),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 5,
    ACTIONS(11), 1,
      ts_builtin_sym_end,
    ACTIONS(15), 1,
      aux_sym_assignment_token1,
    STATE(15), 1,
      sym_value,
    ACTIONS(17), 2,
      sym_quoted_value,
      sym_unquoted_value,
    ACTIONS(13), 3,
      sym_section_header,
      sym_key,
      sym_comment,
  [19] = 5,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    ACTIONS(23), 1,
      aux_sym_assignment_token1,
    STATE(17), 1,
      sym_value,
    ACTIONS(17), 2,
      sym_quoted_value,
      sym_unquoted_value,
    ACTIONS(21), 3,
      sym_section_header,
      sym_key,
      sym_comment,
  [38] = 4,
    ACTIONS(25), 1,
      ts_builtin_sym_end,
    STATE(18), 1,
      sym_value,
    ACTIONS(17), 2,
      sym_quoted_value,
      sym_unquoted_value,
    ACTIONS(27), 3,
      sym_section_header,
      sym_key,
      sym_comment,
  [54] = 4,
    ACTIONS(19), 1,
      ts_builtin_sym_end,
    STATE(17), 1,
      sym_value,
    ACTIONS(17), 2,
      sym_quoted_value,
      sym_unquoted_value,
    ACTIONS(21), 3,
      sym_section_header,
      sym_key,
      sym_comment,
  [70] = 4,
    ACTIONS(7), 1,
      sym_key,
    ACTIONS(31), 1,
      sym_comment,
    ACTIONS(29), 2,
      ts_builtin_sym_end,
      sym_section_header,
    STATE(8), 2,
      sym_assignment,
      aux_sym_section_repeat1,
  [85] = 4,
    ACTIONS(7), 1,
      sym_key,
    ACTIONS(35), 1,
      sym_comment,
    ACTIONS(33), 2,
      ts_builtin_sym_end,
      sym_section_header,
    STATE(9), 2,
      sym_assignment,
      aux_sym_preamble_repeat1,
  [100] = 4,
    ACTIONS(7), 1,
      sym_key,
    ACTIONS(39), 1,
      sym_comment,
    ACTIONS(37), 2,
      ts_builtin_sym_end,
      sym_section_header,
    STATE(10), 2,
      sym_assignment,
      aux_sym_section_repeat1,
  [115] = 4,
    ACTIONS(43), 1,
      sym_key,
    ACTIONS(46), 1,
      sym_comment,
    ACTIONS(41), 2,
      ts_builtin_sym_end,
      sym_section_header,
    STATE(9), 2,
      sym_assignment,
      aux_sym_preamble_repeat1,
  [130] = 4,
    ACTIONS(51), 1,
      sym_key,
    ACTIONS(54), 1,
      sym_comment,
    ACTIONS(49), 2,
      ts_builtin_sym_end,
      sym_section_header,
    STATE(10), 2,
      sym_assignment,
      aux_sym_section_repeat1,
  [145] = 3,
    ACTIONS(5), 1,
      sym_section_header,
    ACTIONS(57), 1,
      ts_builtin_sym_end,
    STATE(13), 2,
      sym_section,
      aux_sym_source_file_repeat1,
  [156] = 3,
    ACTIONS(5), 1,
      sym_section_header,
    ACTIONS(57), 1,
      ts_builtin_sym_end,
    STATE(16), 2,
      sym_section,
      aux_sym_source_file_repeat1,
  [167] = 3,
    ACTIONS(59), 1,
      ts_builtin_sym_end,
    ACTIONS(61), 1,
      sym_section_header,
    STATE(13), 2,
      sym_section,
      aux_sym_source_file_repeat1,
  [178] = 1,
    ACTIONS(64), 4,
      ts_builtin_sym_end,
      sym_section_header,
      sym_key,
      sym_comment,
  [185] = 1,
    ACTIONS(66), 4,
      ts_builtin_sym_end,
      sym_section_header,
      sym_key,
      sym_comment,
  [192] = 3,
    ACTIONS(5), 1,
      sym_section_header,
    ACTIONS(68), 1,
      ts_builtin_sym_end,
    STATE(13), 2,
      sym_section,
      aux_sym_source_file_repeat1,
  [203] = 1,
    ACTIONS(70), 4,
      ts_builtin_sym_end,
      sym_section_header,
      sym_key,
      sym_comment,
  [210] = 1,
    ACTIONS(72), 4,
      ts_builtin_sym_end,
      sym_section_header,
      sym_key,
      sym_comment,
  [217] = 2,
    ACTIONS(74), 1,
      aux_sym_assignment_token1,
    ACTIONS(76), 1,
      anon_sym_EQ,
  [224] = 1,
    ACTIONS(78), 1,
      ts_builtin_sym_end,
  [228] = 1,
    ACTIONS(80), 1,
      anon_sym_EQ,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 19,
  [SMALL_STATE(4)] = 38,
  [SMALL_STATE(5)] = 54,
  [SMALL_STATE(6)] = 70,
  [SMALL_STATE(7)] = 85,
  [SMALL_STATE(8)] = 100,
  [SMALL_STATE(9)] = 115,
  [SMALL_STATE(10)] = 130,
  [SMALL_STATE(11)] = 145,
  [SMALL_STATE(12)] = 156,
  [SMALL_STATE(13)] = 167,
  [SMALL_STATE(14)] = 178,
  [SMALL_STATE(15)] = 185,
  [SMALL_STATE(16)] = 192,
  [SMALL_STATE(17)] = 203,
  [SMALL_STATE(18)] = 210,
  [SMALL_STATE(19)] = 217,
  [SMALL_STATE(20)] = 224,
  [SMALL_STATE(21)] = 228,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [11] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 2, 0, 2),
  [13] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 2, 0, 2),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 3, 0, 2),
  [21] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 3, 0, 2),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [25] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 4, 0, 2),
  [27] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_assignment, 4, 0, 2),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 1, 0, 1),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_preamble, 1, 0, 0),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [37] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 2, 0, 1),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [41] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_preamble_repeat1, 2, 0, 0),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_preamble_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [46] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_preamble_repeat1, 2, 0, 0), SHIFT_REPEAT(9),
  [49] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0),
  [51] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [54] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [57] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [59] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [61] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_value, 1, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 3, 0, 3),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 2, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 4, 0, 4),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_assignment, 5, 0, 5),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [76] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [78] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_systemd(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "systemd",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
